services:
  redis:
    image: redis:7
    command: redis-server --requirepass "authredis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-network
    env_file:
      - local.env
  pg:
    image: postgres:17.2-alpine3.20
    env_file:
      - "local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  auth-service:

volumes:
  redis-data:
  postgres_volume:

networks:
  chat-network:
    driver: bridge