global:
  scrape_interval: 2s
  evaluation_interval: 2s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]

  - job_name: "chat"
    static_configs:
      - targets: ["chat-service:2112"]

  - job_name: "auth"
    static_configs:
      - targets: ["auth-service:2113"]
