version: "3"

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:17.2-alpine3.20
    env_file:
      - "local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
